apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdsyneca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdsyneca
  template:
    metadata:
      labels:
        app: hdsyneca
    spec:
      containers:
      - image: okteto.dev/hdsyneca:latest
        name: hdsyneca
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "77fe2d9f-a2a8-4397-ba09-c4bb83ec7741"
        - name: Vless_Path
          value: "/vl6hbdw55"
        - name: Vmess_UUID
          value: "77fe2d9f-a2a8-4397-ba09-c4bb83ec7741"
        - name: Vmess_Path
          value: "/vm64df3g6"
        - name: Share_Path
          value: "/v2link"
